module.exports = [
	{ 
		alt: null,
		url: "./images/projects/landing_01.png",
		type: 'image',
		sort: 1,
		post_id: 1,
	},
	{ 
		alt: null,
		url: "./images/projects/landing_02.png",
		type: 'image',
		sort: 2,
		post_id: 1,
	},
	{ 
		alt: null,
		url: "./images/projects/landing_03.png",
		type: 'image',
		sort: 3,
		post_id: 1,
	},
	{ 
		alt: null,
		url: "./images/projects/hopfinder_01.png",
		type: 'image',
		sort: 1,
		post_id: 2,
	},
	{ 
		alt: null,
		url: "./images/projects/hopfinder_02.png",
		type: 'image',
		sort: 2,
		post_id: 2,
	},
	{ 
		alt: null,
		url: "./images/projects/hopfinder_03.png",
		type: 'image',
		sort: 3,
		post_id: 2,
	},{ 
		alt: null,
		url: "Beer",
		type: 'component',
		sort: 4,
		post_id: 2,
	},{ 
		alt: null,
		url: "./images/projects/bisque_01.png",
		type: 'image',
		sort: 1,
		post_id: 3,
	},
	{ 
		alt: null,
		url: "./images/projects/bisque_02.png",
		type: 'image',
		sort: 2,
		post_id: 3,
	},
	{ 
		alt: null,
		url: "./images/projects/bisque_03.png",
		type: 'image',
		sort: 3,
		post_id: 3,
	},{ 
		alt: null,
		url: "./images/projects/bisque_04.png",
		type: 'image',
		sort: 4,
		post_id: 3,
	}
];